# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='private'),
        ),
        migrations.AddField(
            model_name='surveygroup',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='private'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surveys',
            field=models.ManyToManyField(blank=True, related_name='surveys', to='assessment.Survey', verbose_name='surveys'),
        ),
    ]
