# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_remove_surveytranslation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='of_type',
            field=models.CharField(choices=[('tf', 'true or false'), ('mc', 'multiple choice'), ('txt', 'text')], default='tf', max_length=3, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='questiontranslation',
            name='question',
            field=models.TextField(verbose_name='question'),
        ),
    ]
