apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-assessment-ingress
spec:
  rules:
  - host: "django-assessment.vandorp.home"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: django-assessment-service
            port:
              number: 5000
